# Generated by Django 3.2.8 on 2021-10-30 13:54

import blog.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=blog.models.random_string, max_length=99999, null=True, verbose_name='کد آگهی')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان آگهی')),
                ('slug', models.SlugField(allow_unicode=True, help_text='عنوان ادرس سایت بهتر است مانند عنوان آگهی باشد (به ازای هر فاصله - بزنید)', max_length=200, unique=True, verbose_name='آدرس سایت')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='در توضیحات آگهی به مواردی مانند شرایط اجاره، جزئیات و ویژگی\u200cهای قابل توجه، امکانات ملک اشاره کنید.', null=True, verbose_name='توضیحات')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], help_text='وضعیت ملک ها را مشخص کنید', max_length=1, verbose_name='وضعیت')),
                ('property_contract', models.CharField(choices=[('-------', '-------'), ('اجاره', 'اجاره'), ('خرید', 'خرید')], default=(('-------', '-------'), ('اجاره', 'اجاره'), ('خرید', 'خرید')), max_length=20, verbose_name='نوع آگهی')),
                ('property_type', models.CharField(choices=[('-------', '-------'), ('آپارتمان', 'آپارتمان'), ('خانه و ویلا', 'خانه و ویلا'), ('زمین/کلنگی', 'زمین/کلنگی'), ('متفرقه', 'متفرقه'), ('مسکونی', 'مسکونی'), ('اداری و تجاری', 'اداری و تجاری')], default='-------', max_length=40, verbose_name='نوع ملک')),
                ('unit_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت / ودیعه')),
                ('Deposit2', models.PositiveIntegerField(blank=True, help_text='اگر نوع آگهی شما مربوط به خرید و فروش هست این قسمت را رها کنید', null=True, verbose_name='اجاره')),
                ('Deposit1', models.BooleanField(default=False, help_text='اگر نوع آگهی شما مربوط به خرید و فروش هست این قسمت را رها کنید', verbose_name='رهن کامل')),
                ('Agree_unit', models.BooleanField(default=False, verbose_name='قیمت توافقی')),
                ('Special', models.BooleanField(default=False, verbose_name='ملک مفت')),
                ('Special2', models.BooleanField(default=False, verbose_name='در صفحه اول ملک مفت')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='تعداد اتاق')),
                ('area', models.PositiveIntegerField(default=0, verbose_name='متراژ')),
                ('foundation', models.PositiveIntegerField(blank=True, default=0, verbose_name='زیربنا')),
                ('year_built', models.PositiveIntegerField(blank=True, default=0, verbose_name='سال ساخت')),
                ('region', models.CharField(max_length=300, verbose_name='منطقه')),
                ('address', models.CharField(blank=True, max_length=20000, verbose_name='آٔدرس')),
                ('construction_contract', models.CharField(blank=True, choices=[('-------', '-------'), ('اسکله بتن', 'اسکله بتن'), ('شناژ', 'شناژ'), ('فلزی', 'فلزی')], default='-------', max_length=20, null=True, verbose_name='نوع ساخت')),
                ('document_contract', models.CharField(blank=True, choices=[('-------', '-------'), ('سند مفروز', 'سند مفروز'), ('سند مشاع', 'سند مشاع'), ('سند شش دانگ', 'سند شش دانگ'), ('سند منگوله دار', 'سند منگوله دار'), ('سند تک برگ', 'سند تک برگ'), ('سند اعیان', 'سند اعیان'), ('سند عرصه', 'سند عرصه'), ('سند وقفی', 'سند وقفی'), ('سند ورثه\u200cای', 'سند ورثه\u200cای'), ('سند المثنی', 'سند المثنی'), ('سند معارض', 'سند معارض'), ('سند شورایی', 'سند شورایی'), ('سند وکالتی', 'سند وکالتی'), ('سند بنچاق', 'سند بنچاق'), ('سند رهنی', 'سند رهنی')], default='-------', max_length=20, null=True, verbose_name='نوع سند')),
                ('conditions_contract', models.CharField(blank=True, choices=[('-------', '-------'), ('قابل تبدیل', 'قابل تبدیل'), ('معاوضه', 'معاوضه'), ('مشارکتی', 'مشارکتی'), ('پیش فروش', 'پیش فروش'), ('وضعیت اداری', 'وضعیت اداری'), ('وام دار', 'وام دار'), ('قدرالسهم', 'قدرالسهم'), ('پاساژ', 'پاساژ'), ('مال', 'مال'), ('باسازی شده', 'باسازی شده')], default='-------', max_length=30, null=True, verbose_name='شرایط')),
                ('direction_contract', models.CharField(blank=True, choices=[('-------', '-------'), ('درب به ساختمان ', 'درب به ساختمان '), ('درب به حیاط ', 'درب به حیاط ')], default='-------', max_length=20, null=True, verbose_name='جهت ساختمان')),
                ('frontage_contract', models.CharField(blank=True, choices=[('-------', '-------'), ('نمای آجری', 'نمای آجری'), ('نمای کامپوزیت', 'نمای کامپوزیت'), ('نمای سنگ', 'نمای سنگ'), ('نمای چوبی', 'نمای چوبی'), ('نمای اتیکس', 'نمای اتیکس'), ('نمای سرامیکی', 'نمای سرامیکی'), ('نمای شیشه ای', 'نمای شیشه ای'), ('نمای مینرال', 'نمای مینرال'), ('نما رومی', 'نما رومی'), ('نانو نما ', 'نانو نما '), (' نمای کنیتکس', ' نمای کنیتکس')], default='-------', max_length=20, null=True, verbose_name='نمای ساختمان')),
                ('cooling_contract', models.CharField(blank=True, choices=[('-------', '-------'), ('دارد', 'دارد'), ('کولر آبی', 'کولر آبی'), ('فن کويل', 'فن کويل'), ('اسپلیت', 'اسپلیت'), ('داکت اسپلیت', 'داکت اسپلیت'), ('کولر گازی', 'کولر گازی')], default='-------', max_length=20, null=True, verbose_name='سیستم سرمایشی')),
                ('heating_contract', models.CharField(blank=True, choices=[('-------', '-------'), ('دارد', 'دارد'), ('از کف', 'از کف'), ('بخاری', 'بخاری'), ('شومینه', 'شومینه'), ('اسپلیت', 'اسپلیت'), ('داکت اسپلیت', 'داکت اسپلیت'), ('فن کویل', 'فن کویل'), ('پکیج', 'پکیج')], default='-------', max_length=20, null=True, verbose_name='سیستم گرمایشی')),
                ('water_contract', models.CharField(blank=True, choices=[('-------', '-------'), ('دارد', 'دارد'), ('آبگرمکن', 'آبگرمکن'), ('پکیج', 'پکیج'), ('موتورخانه', 'موتورخانه')], default='-------', max_length=20, null=True, verbose_name='آب گرم')),
                ('covering_contract', models.CharField(blank=True, choices=[('-------', '-------'), ('دارد', 'دارد'), ('فرش و موکت', 'فرش و موکت'), ('کاشی و موزاییک', 'کاشی و موزاییک'), ('سنگ', 'سنگ'), ('سرامیک', 'سرامیک'), ('بتنی', 'بتنی'), ('PVC', 'PVC'), ('بامبو', 'بامبو'), ('پارکت و لمینت', 'پارکت و لمینت')], default='-------', max_length=20, null=True, verbose_name='جنس کف')),
                ('Parking_lots', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='پارکینگ')),
                ('floor', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='طبقه')),
                ('advertiser', models.CharField(choices=[('شخصی', 'شخصی'), ('مشاور املاک', 'مشاور املاک')], default=(('شخصی', 'شخصی'), ('مشاور املاک', 'مشاور املاک')), max_length=30, verbose_name='آگهی دهنده')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن آگهی دهنده')),
                ('full_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام و نام خانوادگی آگهی دهنده')),
                ('thumbnail', models.ImageField(blank=True, help_text='این قسمت واجب است وارد کنید', null=True, upload_to='image', verbose_name='عکس کاور و اصلی')),
                ('photo_1', models.ImageField(blank=True, default='#', null=True, upload_to='image')),
                ('photo_2', models.ImageField(blank=True, default='#', null=True, upload_to='image')),
                ('photo_3', models.ImageField(blank=True, default='#', null=True, upload_to='image')),
                ('photo_4', models.ImageField(blank=True, default='#', null=True, upload_to='image')),
                ('photo_5', models.ImageField(blank=True, default='#', null=True, upload_to='image')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نماینده')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': ' ملک ها ',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='image', verbose_name='اضافه کردن عکس های بیشتر ')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(max_length=100, verbose_name='انتشار')),
                ('position', models.PositiveIntegerField(verbose_name='شماره')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='خانواده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': ' دسته بندی ها ',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='blog.Category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='همان دسته بندی های انتخاب شده را بنویسید', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='املاک مرتبط'),
        ),
    ]
